INSERT INTO card (name, description, cost, attack, defense, card_type, land_type)
VALUES ('Ancient Scholar',
        'FLOOP >>> Return a random Rainbow card from your discard pile to your hand. If you control a Building in this Lane, gain 1 Action.',
        1, 1, 7, 'CREATURE', 'BLUE_PLAINS'),
       ('Cool Dog', 'Your Creatures on adjacent Lanes may not be Attacked.', 2, 2, 7, 'CREATURE', 'BLUE_PLAINS'),
       ('Dragon Claw', 'FLOOP >>> Move a Creature you control to an empty Lane.', 1, 1, 8, 'CREATURE', 'BLUE_PLAINS'),
       ('Embarrassing Bard', 'FLOOP >>> Draw a card for each Flooped Creature you control (including this one).', 2, 1,
        5, 'CREATURE', 'BLUE_PLAINS'),
       ('Gnome Snot', 'Draw 3 cards.', 1, null, null, 'SPELL', 'BLUE_PLAINS'),
       ('Heavenly Gazer', 'FLOOP >>> Put a Spell from your discard pile on top of your deck.', 1, 2, 5, 'CREATURE',
        'BLUE_PLAINS'),
       ('Psionic Architect', 'When Psionic Architect enters play, you may ready a Flooped Creature you control.', 1, 2,
        6, 'CREATURE', 'BLUE_PLAINS'),
       ('Punk Cat', 'Each Creature that changed Lanes this turn has +2 ATK his turn.', 1, 2, 6, 'CREATURE',
        'BLUE_PLAINS'),
       ('Schoolhouse',
        'FLOOP >>> Your Creature in this Lane loses all abilities and gains the FLOOP ability of a random Creature (with a FLOOP ability) in your discard pile.',
        1, null, null, 'BUILDING', 'BLUE_PLAINS'),
       ('Struzann Jinn', '+2 ATK for each Flooped Creature you control.', 2, 1, 11, 'CREATURE', 'BLUE_PLAINS'),
       ('Uni-Knight', 'Pay 1 Action >>> Target Creature in this Lane has -10 ATK.', 1, 3, 4, 'CREATURE', 'BLUE_PLAINS'),
       ('Woad Mobile Home', 'FLOOP >>> Move a Creature in an adjacent Lane to this Lane (if empty).', 1, null, null,
        'BUILDING', 'BLUE_PLAINS'),
       ('Woadic Chief', 'Woadic Chief has +2 ATK this turn for each Spell you have played this turn.', 2, 2, 10,
        'CREATURE', 'BLUE_PLAINS'),
       ('Woadic Marauder', 'When Woadic Marauder changes Lanes during a turn, draw a card.', 2, 3, 9, 'CREATURE',
        'BLUE_PLAINS'),
       ('X-Large Spirit Soldier', 'Each adjacent Creature has +1 ATK.', 1, 1, 9, 'CREATURE', 'BLUE_PLAINS'),
       ('Blood Fortress', 'Your Creature in this Lane has +1 ATK.', 1, null, null, 'BUILDING', 'RAINBOW'),
       ('Celestial Castle', 'Your Creature in this Lane has +3 DEF.', 1, null, null, 'BUILDING', 'RAINBOW'),
       ('Cerebral Bloodstorm', 'Deal 1 Damage to each opposing Creature.', 1, null, null, 'SPELL', 'RAINBOW'),
       ('Nice Ice Baby', '+3 ATK while your opponent does not control a Creature in this Lane.', 0, 1, 2, 'CREATURE',
        'RAINBOW'),
       ('Teleport', 'Move one of your Creatures to one of your empty Lanes.', 0, null, null, 'SPELL', 'RAINBOW'),
       ('The Pig', 'FLOOP >>> Flip target Cornfield Landscape in this Lane face down.', 1, 1, 4, 'CREATURE', 'RAINBOW'),
       ('Woad Blood', 'Each Creature that changed Lanes this turn has +2 ATK this turn.', 0, null, null, 'SPELL',
        'RAINBOW'),
       ('Woad Talisman', 'Target Blue Plains Creature you control has +2 ATK this turn.', 0, null, null, 'SPELL',
        'RAINBOW');